<?xml version="1.0"?>

<robot name="terabot" xmlns:xacro="http://www.ros.org/wiki/xacro">


  <xacro:property name="PI" value="3.1415926535897931"/>

  <xacro:property name="chassisHeight" value="0.1"/>
  <xacro:property name="chassisLength" value="0.3"/>
  <xacro:property name="chassisWidth" value="0.16"/>
  <xacro:property name="chassisMass" value="1.5"/>

  <xacro:property name="casterRadius" value="0.05"/>
  <xacro:property name="casterMass" value="0.005"/>

  <xacro:property name="wheelWidth" value="0.05"/>
  <xacro:property name="wheelRadius" value="0.1"/>
  <xacro:property name="wheelPos" value="0.2"/>
  <xacro:property name="wheelMass" value="0.1"/>

  <xacro:property name="cameraSize" value="0.05"/>
  <xacro:property name="cameraMass" value="0.1"/>

  <xacro:property name="depthCameraJointHeight" value="0.1"/>

  <xacro:include filename="$(find terabot_description)/urdf/terabot.gazebo" />
  <xacro:include filename="$(find terabot_description)/urdf/materials.xacro" />
  <xacro:include filename="$(find terabot_description)/urdf/macros.xacro" />

  <link name="chassis">
    <collision>
      <origin xyz="0 0 ${wheelRadius}" rpy="0 0 0"/>
      <geometry>
	<box size="${chassisLength} ${chassisWidth} ${chassisHeight}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${wheelRadius}" rpy="0 0 0"/>
      <geometry>
	<box size="${chassisLength} ${chassisWidth} ${chassisHeight}"/>
      </geometry>
      <material name="orange"/>
    </visual>
  </link>

  <!-- Interial link stores the robot's inertial information -->
  <link name="inertial_link">
     <inertial>
      <origin xyz="0 0 ${wheelRadius}" rpy="0 0 0"/>
      <mass value="${chassisMass}"/>
      <xacro:box_inertia m="${chassisMass}" x="${chassisLength}" y="${chassisWidth}" z="${chassisHeight}"/>
    </inertial>
  </link>

  <joint name="inertial_joint" type="fixed">
    <origin xyz="0 0 ${wheelRadius}" rpy="0 0 0" />
    <parent link="chassis" />
    <child link="inertial_link" />
  </joint>

  <!-- depth camera -->
  <joint name="depth_camera_joint" type="fixed">
    <origin xyz="0 0 ${depthCameraJointHeight+wheelRadius+chassisHeight/2}" rpy="0 0 0"/>
    <parent link="chassis"/>
    <child link="depth_camera"/>
  </joint>

  <link name="depth_camera">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="${cameraSize} ${cameraSize} ${cameraSize}"/>
      </geometry>
    </collision>

    <!--visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="${cameraSize} ${cameraSize} ${cameraSize}"/>
      </geometry>
      <material name="red"/>
    </visual-->
    <visual>
      <geometry>
          <mesh filename="package://terabot_description/meshes/realsense_r200.dae"/>
      </geometry>
    </visual>

    <inertial>
      <mass value="${cameraMass}" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <xacro:box_inertia m="${cameraMass}" x="${cameraSize}" y="${cameraSize}" z="${cameraSize}" />
    </inertial>
  </link>

  <joint name="depth_camera_optical_joint" type="fixed">
    <origin xyz="0 0 0" rpy="${-PI/2} 0 ${-PI/2}"/>
    <parent link="depth_camera"/>
    <child link="depth_camera_frame_optical"/>
  </joint>

  <link name="depth_camera_frame_optical"/>

  <!-- caster wheel -->
  <joint name="caster_wheel_joint" type="fixed">
    <parent link="chassis"/>
    <child link="caster_wheel"/>
  </joint>

  <link name="caster_wheel">

    <collision>
      <origin xyz="${casterRadius-chassisLength/2} 0 ${casterRadius-chassisHeight+wheelRadius}" rpy="0 0 0"/>
      <geometry>
	<sphere radius="${casterRadius}"/>
      </geometry>
    </collision>
  
    <visual> 
      <origin xyz="${casterRadius-chassisLength/2} 0 ${casterRadius-chassisHeight+wheelRadius}" rpy="0 0 0"/>
      <geometry>
	<sphere radius="${casterRadius}"/>
      </geometry>
    </visual>

    <inertial>
      <origin xyz="${casterRadius-chassisLength/2} 0 ${casterRadius-chassisHeight+wheelRadius}" rpy="0 0 0"/>
      <mass value="${casterMass}"/>
      <xacro:sphere_inertia m="${casterMass}" r="${casterRadius}"/>
    </inertial>
  </link>

  <!-- differential wheels -->
  <xacro:wheel lr="left" tY="-1"/>
  <xacro:wheel lr="right" tY="1"/>

  <!-- camera -->
  <joint name="camera_joint" type="fixed">
    <origin xyz="${-cameraSize+chassisLength/2} 0 ${cameraSize+wheelRadius+cameraSize/2}" rpy="0 0 0"/>
    <parent link="chassis"/>
    <child link="camera"/>
  </joint>

  <link name="camera">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="${cameraSize} ${cameraSize} ${cameraSize}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="${cameraSize} ${cameraSize} ${cameraSize}"/>
      </geometry>
      <material name="blue"/>
    </visual>

    <inertial>
      <mass value="${cameraMass}" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <xacro:box_inertia m="${cameraMass}" x="${cameraSize}" y="${cameraSize}" z="${cameraSize}" />
    </inertial>
  </link>

</robot>
