odom_frame: odom
base_link_frame: base_link
world_frame: odom

two_d_mode: true

frequency: 50

odom0: mobile_base_controller/odom
odom0_config: [false, false, false,
               false, false, false,
               true, true, true,
               false, false, true,
               false, false, false]
odom0_differential: false
odom0_queue_size: 20

imu0: /camera/accel/sample
imu0_config: [false, false, false,
              true, true, true,
              false, false, false,
              true, true, true,
              false, false, false]
imu0_differential: true
imu0_queue_size: 20
imu0_remove_gravitational_acceleration: true

publish_tf: true
# transform_time_offset: 0.05
# publish_acceleration: false

# initial_state: [0.0,  0.0,  0.0,
#                 0.0,  0.0,  0.0,
#                 0.0,  0.0,  0.0,
#                 0.0,  0.0,  0.0,
#                 0.0,  0.0,  0.0]